### ISSUE TITLE
Nested objects

### ISSUE THREAD

**Issue by samouds** [ediket/graphql-relay-example#1]
Hello,

I have a table that looks like this : 

`{
"capital":  "Accra" ,
"cities": [
{
"asciiname":  "Yendi" ,
"coordinates": {
"elevation": 0 ,
"latitude": 9.44272 ,
"longitude": -0.00991
} ,
"country":  "GH" ,
"geonameid": 2293801 ,
"name":  "Yendi" ,
"timezone":  "Africa/Accra"
} ,
{
"asciiname":  "Winneba" ,
"coordinates": {
"elevation": 0 ,
"latitude": 5.35113 ,
"longitude": -0.62313
} ,
"country":  "GH" ,
"geonameid": 2294034 ,
"name":  "Winneba" ,
"timezone":  "Africa/Accra"
} ,
...]`

How would you adapt your example to do it ? I have no idea how to.

**Comment by ironhee** [comment]
Hi, 

Ok I will try and adapt example to do that :D

**Comment by ironhee** [comment]
Hi,

In that case, just define your table schema like this

```js
const someTable = env.createTable({
  tableName: 'SomeTable',
  schema: () => ({
    capital: Joi.string().required(),
    cities: Joi.array().items(
      Joi.object({
        asciiname: Joi.string(),
        coordinates: Joi.object({
          elevation: Joi.number(),
          latitude: Joi.number(),
          longitude: Joi.number(),
        }),
        country: Joi.string(),
        geonameid: Joi.number().integer(),
        name: Joi.string(),
        timezone: Joi.string(),
      })
    ),
  }),
});
```

[getGraphQLFieldsFromTable](https://github.com/ediket/nothinkdb-graphql/blob/master/src/field.js#L30) will automatically generate GraphQL fields. (`array` to `GraphQLArray`, `object` to `GraphQLObject`, `string` to `GraphQLString`...)

In this project, [this part](https://github.com/ediket/graphql-relay-rethinkdb-example/blob/master/src/graphql/types/userType.js#L19) is use that function.

If you don't like __magic__, Just define Plain GraphQL Field. 

```js
const coordinateType = new GraphQLObjectType({
  name: 'Coordinate',
  fields: () => ({
    capital: {
      elevation: { type: GraphQLFloat },
      latitude: { type: GraphQLFloat },
      longitude: { type: GraphQLFloat },
    },
  }),
});

const cityType = new GraphQLObjectType({
  name: 'City',
  interfaces: [nodeInterface],
  fields: () => ({
    capital: {
      asciiname: { type: GraphQLString },
      coordinates: { type: coordinateType },
      country: { type: GraphQLString },
      geonameid: { type: GraphQLInt },
      name: { type: GraphQLString },
      timezone: { type: GraphQLString },
    },
  }),
});

const someType = new GraphQLObjectType({
  name: 'Something',
  interfaces: [nodeInterface],
  fields: () => ({
    capital: { type: GraphQLString },
    cities: { type: new GraphQLList(cityType) },
  }),
});
```

If you do not understand it well, please feel free to ask. :D 
Thank you!
